apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/oves-ahmed/pet-clinic.git'
    targetRevision: HEAD
    path: base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petclinic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true